Py3: Migrate coherence to py3
klaussfreire/chorde pull request #38
Opened 2022-12-12 20:43 UTC by klaussfreire

This PR makes coherence protocol work in python 3.

Some tests were testing unsupported features of some clients, so they were removed.

Most of the changes involve bytes vs unicode.

2022-12-22 15:11 UTC, gefarion approved these changes

2022-12-22 15:24 UTC, valchulen requested changes

2022-12-22 15:24 UTC, valchulen commented on lib/chorde/mq/ipsub/base.py
> +        if isinstance(prefix, unicode):
```suggestion
        if isinstance(prefix, str):
```

2022-12-22 15:24 UTC, valchulen commented on lib/chorde/mq/ipsub/base.py
> +        if isinstance(prefix, unicode):
```suggestion
        if isinstance(prefix, str):
```

2022-12-22 15:24 UTC, valchulen commented on lib/chorde/mq/ipsub/ipsub_zmq.py
> +        if isinstance(prefix, unicode):
```suggestion
        if isinstance(prefix, str):
```

2022-12-22 15:47 UTC, valchulen approved these changes

2022-12-29 18:17 UTC, gefarion approved these changes

2022-12-29 18:18 UTC, merged